=== EmmanuelCruz/Taqueria_Galactica/src/BaseDeDatos/Tacos.dtd
<!--Archivo que describe los tacos de una taquería.
    Author Cruz Hernández Emmanuel y Karem Ramos Calpulalpan.
    Version Octubre 2019
  -->
<!ELEMENT taqueria (#PCDATA)>
<!ELEMENT taco (#PCDATA)>
<!ATTLIST taco nombre CDATA #REQUIRED>
<!ATTLIST taco descripcion CDATA #REQUIRED>
<!ATTLIST taco precio CDATA #REQUIRED>

=== EmmanuelCruz/Taqueria_Galactica/src/BaseDeDatos/TaqueriaMercurio.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE taqueria SYSTEM "Tacos.dtd">
<taqueria>
  <taco nombre="Alex Sirvent" descripcion="Carne Roquienta, Piedras Galácticas y Queso de la Luna" precio="10.50"/>
  <taco nombre="Héctor Ugarte" descripcion="Pan de Centeno, Carne Vialáctica y Queso de la Luna" precio="45.50"/>
  <taco nombre="Dany Merlo" descripcion="Carne Selecta, Chiles Mercurianos y Queso de la Luna" precio="43.50"/>
  <taco nombre="Poncho Barbosa" descripcion="Carne Cracteriana, Aros de Saturno y Queso de la Luna" precio="99.00"/>
  <taco nombre="Andrés González" descripcion="Ojo de Marciano de Soya, Lechuga Mercuriana y Queso de la Luna" precio="80.50"/>
  <taco nombre="Urbian Le Verrier" descripcion="Patas Lúgubres, Pimienta Saleriana y  Queso de la Luna" precio="76.00"/>
  <taco nombre="Viento Solar" descripcion="Carne Solerina, Aros de Saturno y Queso de la Luna" precio="87.00"/>
  <taco nombre="Apolo" descripcion="Carne Olimpica, Salsa Cohética y Queso de la Luna" precio="87.00"/>
</taqueria>

=== EmmanuelCruz/Taqueria_Galactica/src/BaseDeDatos/TaqueriaMarte.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE taqueria SYSTEM "Tacos.dtd">
<taqueria>
  <taco nombre="Marcianito Bailador" descripcion="Carne de vaca loca, Lechuga desidratada y polvo de asteroides" precio="10.00"/>
  <taco nombre="Valles Lunares" descripcion="Ojo de vaca loca, Queso de la Luna y Salsa Secreta Alienígena" precio="200.00"/>
  <taco nombre="Está Que Arde" descripcion="Cráter, Jitomate Magnesico, Salsa Volcanica" precio="30.00"/>
  <taco nombre="Ares" descripcion="Carne Verde, Aros de Saturno, Queso de la Luna" precio="40.00"/>
  <taco nombre="Tharsis" descripcion="Mano de Marciano de Soya, Pesuñas de Vaca y Salsa Secreta" precio="23.00"/>
  <taco nombre="A Marte" descripcion="Aros de Saturno, Rimel de miel y Pepinillos de Geosilica" precio="47.50"/>
  <taco nombre="Marci Marte" descripcion="Dedos Marcianicos, Queso de la Luna y Salsa de Estrellas Fugaces" precio="243.50"/>
  <taco nombre="Fuego Ardiente" descripcion="Piedras Ardientes, Aros de Saturno y Estrellas Fugaces" precio="52.00"/>
</taqueria>

=== EmmanuelCruz/Taqueria_Galactica/src/BaseDeDatos/TaqueriaSaturno.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE taqueria SYSTEM "Tacos.dtd">
<taqueria>
  <taco nombre="Señor de los Anillos" descripcion="Aros de Saturno, Carne Maricusi y Queso de la Luna" precio="100.00"/>
  <taco nombre="Encélado" descripcion="Carne de Saturniana, Lechuga Suecaqueji y Aros de Saturno" precio="80.00"/>
  <taco nombre="Titán" descripcion="Carne de Marciano, Aros de Saturno y Salsa Galáctica" precio="30.00"/>
  <taco nombre="Tetis" descripcion="Ojo de Marciano, Lengua de Vaca y Aros de Saturno" precio="40.50"/>
  <taco nombre="Hiperion" descripcion="Pesuñas de Marciano, Nariz de Vaca y Aros de Saturno" precio="99.50"/>
  <taco nombre="Mimas" descripcion="Dedos de Marciano, Chiles Toreados y Aros de Saturno" precio="73.50"/>
  <taco nombre="Dione" descripcion="Patas Chuecas, Salsa de Lengua y Aros de Saturno" precio="84.00"/>
  <taco nombre="Jápeto" descripcion="Carne de Vaca Loca, Salsa Toreada y Aros de Saturno" precio="54.00"/>
  <taco nombre="Rea" descripcion="Nariz de Vaca, Salsa Galáctica y Aros de Saturno" precio="34.50"/>
</taqueria>

=== EmmanuelCruz/Taqueria_Galactica/src/BaseDeDatos/TaqueriaVenus.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE taqueria SYSTEM "Tacos.dtd">
<taqueria>
  <taco nombre="Venustiano Carranza" descripcion="Carne Nitrogenada, LechuVenus, JitoVenus y Queso de la Luna" precio="100.00"/>
  <taco nombre="Diosa del Amor" descripcion="Ácido Sulfúrico, Leche Espacial y Aros de Saturno" precio="202.00"/>
  <taco nombre="Friendzone" descripcion="Carne Ácida, Aros de Saturno y Chiles Toreados" precio="302.00"/>
  <taco nombre="No Eres Tú, Soy Yo" descripcion="Carne Venusiana, Chiles Soplados y Aros de Saturno" precio="401.00"/>
  <taco nombre="Amigos con Derecho" descripcion="Salsa Espacial, LechuVenus y JitoVenus" precio="509.00"/>
  <taco nombre="El Argón" descripcion="Carne Argónica, Salsa Venusiana y Queso de la Luna" precio="320.50"/>
  <taco nombre="Atalanta Planitia" descripcion="Churubusco, Lechusiatocio y Queso de la Luna" precio="321.50"/>
  <taco nombre="Neith" descripcion="Chetos, JitoVenus y Aros de Saturno" precio="875.50"/>
</taqueria>
